-- MySQL Script generated by MySQL Workbench
-- qua 17 dez 2025 00:10:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rankio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rankio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rankio` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `rankio` ;

-- -----------------------------------------------------
-- Table `rankio`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rankio`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `emaill` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `emaill_UNIQUE` (`emaill` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rankio`.`discipline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rankio`.`discipline` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `key` VARCHAR(10) NOT NULL,
  `description` VARCHAR(255) NULL,
  `begin` DATETIME NULL,
  `end` DATETIME NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `fk_class_user_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_class_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `rankio`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rankio`.`activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rankio`.`activity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `discipline_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `text` TEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `discipline_id`),
  INDEX `fk_activity_discipline1_idx` (`discipline_id` ASC) VISIBLE,
  CONSTRAINT `fk_activity_discipline1`
    FOREIGN KEY (`discipline_id`)
    REFERENCES `rankio`.`discipline` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rankio`.`discipline_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rankio`.`discipline_user` (
  `discipline_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`discipline_id`, `user_id`),
  INDEX `fk_user_has_discipline_discipline1_idx` (`discipline_id` ASC) VISIBLE,
  INDEX `fk_user_has_discipline_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_discipline_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `rankio`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_discipline_discipline1`
    FOREIGN KEY (`discipline_id`)
    REFERENCES `rankio`.`discipline` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rankio`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rankio`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `activity_id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `activity_id`),
  INDEX `fk_question_activity1_idx` (`activity_id` ASC) VISIBLE,
  CONSTRAINT `fk_question_activity1`
    FOREIGN KEY (`activity_id`)
    REFERENCES `rankio`.`activity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rankio`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rankio`.`answer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `text` VARCHAR(45) NOT NULL,
  `correct` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `question_id`),
  INDEX `fk_answer_question1_idx` (`question_id` ASC) VISIBLE,
  CONSTRAINT `fk_answer_question1`
    FOREIGN KEY (`question_id`)
    REFERENCES `rankio`.`question` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rankio`.`activity_answer_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rankio`.`activity_answer_user` (
  `id` BIGINT NOT NULL,
  `user_id` INT NOT NULL,
  `activity_id` INT NOT NULL,
  `answer_id` INT NOT NULL,
  `answer_question_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_activity_answer_user_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_activity_answer_user_activity1_idx` (`activity_id` ASC) VISIBLE,
  INDEX `fk_activity_answer_user_answer1_idx` (`answer_id` ASC, `answer_question_id` ASC) VISIBLE,
  CONSTRAINT `fk_activity_answer_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `rankio`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activity_answer_user_activity1`
    FOREIGN KEY (`activity_id`)
    REFERENCES `rankio`.`activity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_activity_answer_user_answer1`
    FOREIGN KEY (`answer_id` , `answer_question_id`)
    REFERENCES `rankio`.`answer` (`id` , `question_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
