-- MySQL Script generated by MySQL Workbench
-- seg 23 fev 2026 23:09:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rankio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rankio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rankio` DEFAULT CHARACTER SET utf8mb3 ;
USE `rankio` ;

-- -----------------------------------------------------
-- Table `rankio`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rankio`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `role` VARCHAR(10) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_2` (`email` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 67
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rankio`.`achievement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rankio`.`achievement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(6) NULL DEFAULT 'bronze',
  `text` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_achievement_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_achievement_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `rankio`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `rankio`.`achievement_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rankio`.`achievement_user` (
  `achievement_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`achievement_id`, `user_id`),
  UNIQUE INDEX `student_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `achievement_id_UNIQUE` (`achievement_id` ASC) VISIBLE,
  INDEX `fk_achievement_has_user_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_achievement_has_user_achievement1_idx` (`achievement_id` ASC) VISIBLE,
  CONSTRAINT `fk_achievement_has_user_achievement1`
    FOREIGN KEY (`achievement_id`)
    REFERENCES `rankio`.`achievement` (`id`),
  CONSTRAINT `fk_achievement_has_user_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `rankio`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `rankio`.`discipline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rankio`.`discipline` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `key` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `discipline_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `rankio`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rankio`.`activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rankio`.`activity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `discipline_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `text` TEXT NULL DEFAULT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT '0',
  `time_limit` TIME NOT NULL DEFAULT 00:00:20,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `discipline_id` (`discipline_id` ASC) VISIBLE,
  CONSTRAINT `activity_ibfk_1`
    FOREIGN KEY (`discipline_id`)
    REFERENCES `rankio`.`discipline` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 55
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rankio`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rankio`.`question` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `activity_id` INT NOT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `text` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `activity_id` (`activity_id` ASC) VISIBLE,
  CONSTRAINT `question_ibfk_1`
    FOREIGN KEY (`activity_id`)
    REFERENCES `rankio`.`activity` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 271
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rankio`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rankio`.`answer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `text` VARCHAR(100) NOT NULL,
  `correct` TINYINT(1) NULL DEFAULT '0',
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `question_id` (`question_id` ASC) VISIBLE,
  CONSTRAINT `answer_ibfk_1`
    FOREIGN KEY (`question_id`)
    REFERENCES `rankio`.`question` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 865
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rankio`.`activity_answer_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rankio`.`activity_answer_user` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `activity_id` INT NOT NULL,
  `answer_id` INT NOT NULL,
  `is_correct` TINYINT(1) NULL DEFAULT 0,
  `answer_time` INT NULL DEFAULT 0,
  `xp` INT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `activity_id` (`activity_id` ASC) VISIBLE,
  INDEX `answer_id` (`answer_id` ASC) VISIBLE,
  CONSTRAINT `activity_answer_user_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `rankio`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `activity_answer_user_ibfk_2`
    FOREIGN KEY (`activity_id`)
    REFERENCES `rankio`.`activity` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `activity_answer_user_ibfk_3`
    FOREIGN KEY (`answer_id`)
    REFERENCES `rankio`.`answer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rankio`.`discipline_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rankio`.`discipline_user` (
  `discipline_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  UNIQUE INDEX `discipline_user_discipline_id_userid_unique` (`discipline_id` ASC, `user_id` ASC) VISIBLE,
  INDEX `discipline_id` (`discipline_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `discipline_user_ibfk_1`
    FOREIGN KEY (`discipline_id`)
    REFERENCES `rankio`.`discipline` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `discipline_user_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `rankio`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `rankio`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rankio`.`migrations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 66
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
